//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleverAge.OdfConverter.OdfWord2007Addin.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleverAge.OdfConverter.OdfWord2007Addin.resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string AllFileType {
            get {
                return ResourceManager.GetString("AllFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not an ODF document..
        /// </summary>
        internal static string NotAnOdfDocumentError {
            get {
                return ResourceManager.GetString("NotAnOdfDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this feature is not yet implemented.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a copy of the document with Open Document Format (ODF)..
        /// </summary>
        internal static string OdfExportDescription {
            get {
                return ResourceManager.GetString("OdfExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as ODF....
        /// </summary>
        internal static string OdfExportLabel {
            get {
                return ResourceManager.GetString("OdfExportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenDocument Text files.
        /// </summary>
        internal static string OdfFileType {
            get {
                return ResourceManager.GetString("OdfFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an Open Document Format (ODF) file..
        /// </summary>
        internal static string OdfImportDescription {
            get {
                return ResourceManager.GetString("OdfImportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ODF....
        /// </summary>
        internal static string OdfImportLabel {
            get {
                return ResourceManager.GetString("OdfImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODF....
        /// </summary>
        internal static string OdfMenuLabel {
            get {
                return ResourceManager.GetString("OdfMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured. Please feel free to fill a bug report on the project web site with your file attached..
        /// </summary>
        internal static string OdfUnexpectedError {
            get {
                return ResourceManager.GetString("OdfUnexpectedError", resourceCulture);
            }
        }
    }
}
